version: "2"

services:
  proxy:
    image: ptrdin/caddy:latest
    ports:
      - 80:80
      - 443:443
      #- 2019:2019
    environment:
      - DOMAIN=loc.alho.st
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_proxy_data:/data
    networks:
      - caddy_proxy

volumes:
  caddy_proxy_data: null

networks:
  caddy_proxy:
    attachable: true
    name: caddy_proxy
