version: "2"

services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    ports:
      - 80:80
      - 443:443
      #- 2019:2019
    environment:
      - DOMAIN=loc.alho.st
      - CADDY_INGRESS_NETWORKS=caddy_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_proxy_data:/data
    networks:
      - caddy_proxy
    restart: unless-stopped

volumes:
  caddy_proxy_data: null

networks:
  caddy_proxy:
    attachable: true
    name: caddy_proxy
