version: "2"

services:
  validator:
    image: cryptoworkbench/solana-amman:v1.11.5
    entrypoint: bash
    command: '-c "source ~/.bashrc && amman start"'
    #environment:
    volumes:
      - data:/data
    networks:
      - caddy_proxy
    labels:
      caddy.tls: "internal"
      caddy: solana.loc.alho.st
      caddy.reverse_proxy: "{{upstreams 8900}}"
      # tell Caddy what port on the container to talk http to
      # virtual.host: "solana"
      # virtual.port: "8900"
    restart: always

volumes:
  data: null

networks:
  caddy_proxy:
    external: true
