version: "2"

services:
  validator:
    image: cryptoworkbench/solana-amman:v1.11.5
    entrypoint: bash
    command: '-c "source ~/.bashrc && amman start"'
    #environment:
    volumes:
      - data:/data
    ports:
      - "8900" # RPC port
      - "8899" # websocket port
    restart: always

volumes:
  data: null
